# Generated by Django 3.0.3 on 2020-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFilesBeaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_number', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='bease_message')),
            ],
            options={
                'db_table': 'info_files_bease_message',
            },
        ),
    ]
